"""
Branch-Protection & PR-Flow.

Vorab-Prüfung der Branch-Protection (Required Checks, kein Force-Push) durchführen;
Draft-PR nur nach allen grünen Gates erstellen; einheitlicher PR-Titel/Text und 
Verlinkung der QA-, SBOM- und Security-Artefakte; sonstiger Abbruch vor PR-Erstellung.
"""

import json
import logging
import subprocess
import sys
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional

# Setup Logging
_log = logging.getLogger(__name__)


@dataclass
class BranchProtectionRule:
    """Branch-Protection-Regel."""
    required_status_checks: List[str] = field(default_factory=list)
    enforce_admins: bool = True
    required_pull_request_reviews: bool = True
    dismiss_stale_reviews: bool = True
    require_code_owner_reviews: bool = False
    restrictions: Optional[Dict] = None
    allow_force_pushes: bool = False
    allow_deletions: bool = False


@dataclass
class PRTemplate:
    """PR-Template mit Artefakt-Links."""
    title_template: str = "[FEATURE] {spec_id}: {title}"
    description_template: str = """## 🚀 Feature Implementation

**Spec ID:** {spec_id}  
**Title:** {title}  
**Timestamp:** {timestamp}  

### 📋 Summary
{description}

### 🎯 Changes
{changes_summary}

### ✅ Quality Gates
{quality_gates_summary}

### 📊 Artifacts
{artifacts_links}

### 🔒 Security & Compliance
{security_summary}

---
*This PR was automatically generated by CodePipeline*
"""


@dataclass
class QualityGateStatus:
    """Status eines Quality Gates."""
    name: str
    passed: bool
    score: Optional[int] = None
    details: Optional[str] = None
    artifacts: List[str] = field(default_factory=list)


@dataclass
class PRCreationResult:
    """Ergebnis der PR-Erstellung."""
    success: bool
    pr_number: Optional[int] = None
    pr_url: Optional[str] = None
    error_message: Optional[str] = None
    branch_name: Optional[str] = None
    artifacts_uploaded: List[str] = field(default_factory=list)


class BranchProtectionPRFlow:
    """Branch-Protection & PR-Flow Management."""
    
    def __init__(self, 
                 repo_owner: str,
                 repo_name: str,
                 spec_id: str,
                 github_token: Optional[str] = None):
        """
        Args:
            repo_owner: GitHub Repository Owner
            repo_name: GitHub Repository Name
            spec_id: Feature-Spec ID
            github_token: GitHub Personal Access Token
        """
        self.repo_owner = repo_owner
        self.repo_name = repo_name
        self.spec_id = spec_id
        self.github_token = github_token
        
        # Branch-Namen
        self.main_branch = "main"
        self.feature_branch = f"feature/{spec_id}"
        
        # Status-Tracking
        self.quality_gates: List[QualityGateStatus] = []
        self.artifacts: Dict[str, str] = {}
        self.branch_protection_verified = False
        
        _log.info(f"[{self.spec_id}] Branch Protection PR Flow initialisiert")
        _log.info(f"[{self.spec_id}] Repo: {repo_owner}/{repo_name}")
        _log.info(f"[{self.spec_id}] Feature Branch: {self.feature_branch}")
    
    def verify_branch_protection(self, branch: str = None) -> bool:
        """
        Verifiziere Branch-Protection-Regeln.
        
        Args:
            branch: Branch-Name (default: main)
            
        Returns:
            True wenn Branch-Protection korrekt konfiguriert
        """
        branch = branch or self.main_branch
        _log.info(f"[{self.spec_id}] Verifiziere Branch-Protection für {branch}")
        
        try:
            # Prüfe Branch-Protection via GitHub API (simuliert)
            protection_status = self._check_branch_protection_api(branch)
            
            if not protection_status["protected"]:
                _log.error(f"[{self.spec_id}] Branch {branch} ist nicht geschützt")
                return False
            
            # Prüfe Required Status Checks
            required_checks = protection_status.get("required_status_checks", [])
            expected_checks = [
                "test-coverage", "security-scan", "license-check", 
                "quality-gates", "build"
            ]
            
            missing_checks = [check for check in expected_checks if check not in required_checks]
            
            if missing_checks:
                _log.warning(f"[{self.spec_id}] Fehlende Required Status Checks: {missing_checks}")
            
            # Prüfe weitere Schutzregeln
            if protection_status.get("allow_force_pushes", True):
                _log.error(f"[{self.spec_id}] Force-Push ist erlaubt - Sicherheitsrisiko!")
                return False
            
            if not protection_status.get("required_pull_request_reviews", False):
                _log.warning(f"[{self.spec_id}] PR-Reviews sind nicht erforderlich")
            
            self.branch_protection_verified = True
            _log.info(f"[{self.spec_id}] Branch-Protection verifiziert: ✅")
            
            return True
            
        except Exception as e:
            _log.error(f"[{self.spec_id}] Branch-Protection-Prüfung fehlgeschlagen: {e}")
            return False
    
    def _check_branch_protection_api(self, branch: str) -> Dict:
        """
        Prüfe Branch-Protection via GitHub API.
        
        Args:
            branch: Branch-Name
            
        Returns:
            Dictionary mit Branch-Protection-Status
        """
        # Simuliere GitHub API-Call
        # In Production: Echter API-Call mit github_token
        
        if not self.github_token:
            _log.warning(f"[{self.spec_id}] Kein GitHub Token - simuliere Branch-Protection")
            
            # Simulierte Branch-Protection (Standard-Konfiguration)
            return {
                "protected": True,
                "required_status_checks": [
                    "test-coverage", "security-scan", "quality-gates"
                ],
                "required_pull_request_reviews": True,
                "dismiss_stale_reviews": True,
                "allow_force_pushes": False,
                "allow_deletions": False,
                "enforce_admins": True
            }
        
        try:
            # Echter GitHub API-Call würde hier stehen
            import requests
            
            headers = {
                "Authorization": f"Bearer {self.github_token}",
                "Accept": "application/vnd.github.v3+json"
            }
            
            url = f"https://api.github.com/repos/{self.repo_owner}/{self.repo_name}/branches/{branch}/protection"
            
            response = requests.get(url, headers=headers, timeout=30)
            
            if response.status_code == 200:
                protection_data = response.json()
                
                return {
                    "protected": True,
                    "required_status_checks": [
                        check["context"] for check in 
                        protection_data.get("required_status_checks", {}).get("contexts", [])
                    ],
                    "required_pull_request_reviews": "required_pull_request_reviews" in protection_data,
                    "dismiss_stale_reviews": protection_data.get("required_pull_request_reviews", {}).get("dismiss_stale_reviews", False),
                    "allow_force_pushes": protection_data.get("allow_force_pushes", {}).get("enabled", False),
                    "allow_deletions": protection_data.get("allow_deletions", {}).get("enabled", False),
                    "enforce_admins": protection_data.get("enforce_admins", {}).get("enabled", False)
                }
            
            elif response.status_code == 404:
                return {"protected": False}
            
            else:
                _log.error(f"[{self.spec_id}] GitHub API Fehler: {response.status_code}")
                return {"protected": False}
                
        except ImportError:
            _log.warning(f"[{self.spec_id}] requests nicht verfügbar - simuliere API")
            return {"protected": True, "required_status_checks": []}
        
        except Exception as e:
            _log.error(f"[{self.spec_id}] GitHub API-Call fehlgeschlagen: {e}")
            return {"protected": False}
    
    def add_quality_gate_result(self, gate_status: QualityGateStatus):
        """Füge Quality Gate-Ergebnis hinzu."""
        self.quality_gates.append(gate_status)
        _log.info(f"[{self.spec_id}] Quality Gate hinzugefügt: {gate_status.name} - "
                 f"{'✅ PASSED' if gate_status.passed else '❌ FAILED'}")
    
    def add_artifact(self, artifact_type: str, artifact_path: str):
        """Füge Artefakt hinzu."""
        self.artifacts[artifact_type] = artifact_path
        _log.info(f"[{self.spec_id}] Artefakt hinzugefügt: {artifact_type} -> {artifact_path}")
    
    def validate_all_gates_green(self) -> bool:
        """Validiere dass alle Quality Gates grün sind."""
        if not self.quality_gates:
            _log.warning(f"[{self.spec_id}] Keine Quality Gates definiert")
            return False
        
        failed_gates = [gate for gate in self.quality_gates if not gate.passed]
        
        if failed_gates:
            _log.error(f"[{self.spec_id}] {len(failed_gates)} Quality Gates fehlgeschlagen:")
            for gate in failed_gates:
                _log.error(f"[{self.spec_id}]   - {gate.name}: {gate.details}")
            return False
        
        _log.info(f"[{self.spec_id}] Alle {len(self.quality_gates)} Quality Gates sind grün ✅")
        return True
    
    def create_feature_branch(self) -> bool:
        """Erstelle Feature-Branch."""
        _log.info(f"[{self.spec_id}] Erstelle Feature-Branch: {self.feature_branch}")
        
        try:
            # Prüfe ob Branch bereits existiert
            result = subprocess.run(
                ["git", "rev-parse", "--verify", self.feature_branch],
                capture_output=True,
                text=True,
                cwd="."
            )
            
            if result.returncode == 0:
                _log.info(f"[{self.spec_id}] Feature-Branch existiert bereits")
                return True
            
            # Erstelle neuen Branch von main
            subprocess.run(
                ["git", "checkout", "-b", self.feature_branch, self.main_branch],
                check=True,
                capture_output=True,
                text=True,
                cwd="."
            )
            
            _log.info(f"[{self.spec_id}] Feature-Branch erstellt: {self.feature_branch}")
            return True
            
        except subprocess.CalledProcessError as e:
            _log.error(f"[{self.spec_id}] Feature-Branch-Erstellung fehlgeschlagen: {e}")
            return False
    
    def push_feature_branch(self) -> bool:
        """Pushe Feature-Branch."""
        _log.info(f"[{self.spec_id}] Pushe Feature-Branch: {self.feature_branch}")
        
        try:
            # Push Branch
            subprocess.run(
                ["git", "push", "-u", "origin", self.feature_branch],
                check=True,
                capture_output=True,
                text=True,
                cwd="."
            )
            
            _log.info(f"[{self.spec_id}] Feature-Branch gepusht: {self.feature_branch}")
            return True
            
        except subprocess.CalledProcessError as e:
            _log.error(f"[{self.spec_id}] Feature-Branch-Push fehlgeschlagen: {e}")
            return False
    
    def generate_pr_content(self, 
                           title: str,
                           description: str,
                           changes_summary: str = None) -> Dict[str, str]:
        """
        Generiere PR-Titel und -Beschreibung.
        
        Args:
            title: Feature-Titel
            description: Feature-Beschreibung
            changes_summary: Zusammenfassung der Änderungen
            
        Returns:
            Dictionary mit PR-Titel und -Beschreibung
        """
        # PR-Titel
        pr_title = f"[FEATURE] {self.spec_id}: {title}"
        
        # Quality Gates Summary
        gates_summary = ""
        for gate in self.quality_gates:
            status_emoji = "✅" if gate.passed else "❌"
            score_info = f" ({gate.score}/100)" if gate.score is not None else ""
            gates_summary += f"- **{gate.name}**: {status_emoji} {'PASSED' if gate.passed else 'FAILED'}{score_info}\n"
        
        # Artifacts Links
        artifacts_links = ""
        for artifact_type, artifact_path in self.artifacts.items():
            artifacts_links += f"- **{artifact_type.title()}**: [`{Path(artifact_path).name}`]({artifact_path})\n"
        
        # Security Summary
        security_gates = [gate for gate in self.quality_gates if "security" in gate.name.lower() or "license" in gate.name.lower()]
        security_summary = ""
        
        if security_gates:
            security_summary = "### 🔒 Security & Compliance Status\n\n"
            for gate in security_gates:
                status_emoji = "✅" if gate.passed else "❌"
                security_summary += f"- **{gate.name}**: {status_emoji} {'COMPLIANT' if gate.passed else 'VIOLATIONS FOUND'}\n"
        else:
            security_summary = "No security scans performed."
        
        # PR-Beschreibung
        pr_description = f"""## 🚀 Feature Implementation

**Spec ID:** {self.spec_id}  
**Title:** {title}  
**Timestamp:** {datetime.now().isoformat()}  

### 📋 Summary
{description or 'No description provided.'}

### 🎯 Changes
{changes_summary or 'Automated feature implementation via CodePipeline.'}

### ✅ Quality Gates Status
{gates_summary if gates_summary else 'No quality gates executed.'}

### 📊 Generated Artifacts
{artifacts_links if artifacts_links else 'No artifacts generated.'}

{security_summary}

### 🔍 Review Checklist
- [ ] Code follows project standards
- [ ] All tests pass
- [ ] Security scan results reviewed
- [ ] License compliance verified
- [ ] Documentation updated

---
*This PR was automatically generated by CodePipeline on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*
"""
        
        return {
            "title": pr_title,
            "description": pr_description
        }
    
    def create_draft_pr(self, 
                       title: str,
                       description: str,
                       changes_summary: str = None) -> PRCreationResult:
        """
        Erstelle Draft-PR mit Artefakt-Links.
        
        Args:
            title: Feature-Titel
            description: Feature-Beschreibung
            changes_summary: Zusammenfassung der Änderungen
            
        Returns:
            PRCreationResult mit Details
        """
        _log.info(f"[{self.spec_id}] Erstelle Draft-PR")
        
        try:
            # 1. Vorab-Prüfungen
            if not self.branch_protection_verified:
                if not self.verify_branch_protection():
                    return PRCreationResult(
                        success=False,
                        error_message="Branch-Protection nicht verifiziert"
                    )
            
            # 2. Quality Gates prüfen
            if not self.validate_all_gates_green():
                return PRCreationResult(
                    success=False,
                    error_message="Nicht alle Quality Gates sind grün"
                )
            
            # 3. Feature-Branch erstellen und pushen
            if not self.create_feature_branch():
                return PRCreationResult(
                    success=False,
                    error_message="Feature-Branch-Erstellung fehlgeschlagen"
                )
            
            if not self.push_feature_branch():
                return PRCreationResult(
                    success=False,
                    error_message="Feature-Branch-Push fehlgeschlagen"
                )
            
            # 4. PR-Content generieren
            pr_content = self.generate_pr_content(title, description, changes_summary)
            
            # 5. Draft-PR erstellen (simuliert)
            pr_result = self._create_github_pr(pr_content)
            
            if pr_result["success"]:
                _log.info(f"[{self.spec_id}] Draft-PR erstellt: #{pr_result['pr_number']}")
                
                return PRCreationResult(
                    success=True,
                    pr_number=pr_result["pr_number"],
                    pr_url=pr_result["pr_url"],
                    branch_name=self.feature_branch,
                    artifacts_uploaded=list(self.artifacts.keys())
                )
            else:
                return PRCreationResult(
                    success=False,
                    error_message=pr_result["error"]
                )
                
        except Exception as e:
            _log.error(f"[{self.spec_id}] Draft-PR-Erstellung fehlgeschlagen: {e}")
            return PRCreationResult(
                success=False,
                error_message=str(e)
            )
    
    def _create_github_pr(self, pr_content: Dict[str, str]) -> Dict:
        """
        Erstelle GitHub PR via API.
        
        Args:
            pr_content: PR-Titel und -Beschreibung
            
        Returns:
            Dictionary mit PR-Erstellungsergebnis
        """
        if not self.github_token:
            _log.warning(f"[{self.spec_id}] Kein GitHub Token - simuliere PR-Erstellung")
            
            # Simuliere erfolgreiche PR-Erstellung
            pr_number = 42  # Beispiel-PR-Nummer
            pr_url = f"https://github.com/{self.repo_owner}/{self.repo_name}/pull/{pr_number}"
            
            # Speichere PR-Content für Review
            pr_file = f"simulated_pr_{self.spec_id}.md"
            with open(pr_file, 'w', encoding='utf-8') as f:
                f.write(f"# {pr_content['title']}\n\n{pr_content['description']}")
            
            _log.info(f"[{self.spec_id}] PR-Content gespeichert: {pr_file}")
            
            return {
                "success": True,
                "pr_number": pr_number,
                "pr_url": pr_url
            }
        
        try:
            # Echter GitHub API-Call würde hier stehen
            import requests
            
            headers = {
                "Authorization": f"Bearer {self.github_token}",
                "Accept": "application/vnd.github.v3+json"
            }
            
            data = {
                "title": pr_content["title"],
                "body": pr_content["description"],
                "head": self.feature_branch,
                "base": self.main_branch,
                "draft": True  # Draft-PR
            }
            
            url = f"https://api.github.com/repos/{self.repo_owner}/{self.repo_name}/pulls"
            
            response = requests.post(url, headers=headers, json=data, timeout=30)
            
            if response.status_code == 201:
                pr_data = response.json()
                
                return {
                    "success": True,
                    "pr_number": pr_data["number"],
                    "pr_url": pr_data["html_url"]
                }
            else:
                return {
                    "success": False,
                    "error": f"GitHub API Error: {response.status_code} - {response.text}"
                }
                
        except ImportError:
            _log.warning(f"[{self.spec_id}] requests nicht verfügbar - simuliere PR")
            return {"success": True, "pr_number": 42, "pr_url": "https://github.com/simulated/pr"}
        
        except Exception as e:
            return {
                "success": False,
                "error": str(e)
            }
    
    def upload_artifacts_to_pr(self, pr_number: int) -> bool:
        """
        Lade Artefakte zu PR hoch (als Kommentar oder Gist).
        
        Args:
            pr_number: PR-Nummer
            
        Returns:
            True wenn erfolgreich
        """
        _log.info(f"[{self.spec_id}] Lade Artefakte zu PR #{pr_number} hoch")
        
        try:
            # Erstelle Artefakt-Zusammenfassung
            artifacts_summary = f"""## 📊 Quality Artifacts for PR #{pr_number}

**Spec ID:** {self.spec_id}  
**Generated:** {datetime.now().isoformat()}

### 📄 Available Artifacts

"""
            
            for artifact_type, artifact_path in self.artifacts.items():
                file_size = Path(artifact_path).stat().st_size if Path(artifact_path).exists() else 0
                artifacts_summary += f"- **{artifact_type.title()}**: `{Path(artifact_path).name}` ({file_size} bytes)\n"
            
            artifacts_summary += "\n### 🔗 Access Instructions\n"
            artifacts_summary += "Artifacts are available in the CI/CD pipeline artifacts or can be downloaded from the build logs.\n"
            
            # In Production: Upload zu GitHub Artifacts oder als PR-Kommentar
            comment_file = f"pr_artifacts_comment_{self.spec_id}.md"
            with open(comment_file, 'w', encoding='utf-8') as f:
                f.write(artifacts_summary)
            
            _log.info(f"[{self.spec_id}] Artefakt-Kommentar gespeichert: {comment_file}")
            
            return True
            
        except Exception as e:
            _log.error(f"[{self.spec_id}] Artefakt-Upload fehlgeschlagen: {e}")
            return False
    
    def generate_status_report(self) -> Dict:
        """Generiere Status-Report für PR-Flow."""
        return {
            "spec_id": self.spec_id,
            "timestamp": datetime.now().isoformat(),
            "branch_protection": {
                "verified": self.branch_protection_verified,
                "main_branch": self.main_branch,
                "feature_branch": self.feature_branch
            },
            "quality_gates": [
                {
                    "name": gate.name,
                    "passed": gate.passed,
                    "score": gate.score,
                    "details": gate.details,
                    "artifacts_count": len(gate.artifacts)
                }
                for gate in self.quality_gates
            ],
            "artifacts": {
                "count": len(self.artifacts),
                "types": list(self.artifacts.keys()),
                "files": list(self.artifacts.values())
            },
            "summary": {
                "all_gates_green": self.validate_all_gates_green(),
                "ready_for_pr": self.branch_protection_verified and self.validate_all_gates_green(),
                "total_gates": len(self.quality_gates),
                "passed_gates": sum(1 for gate in self.quality_gates if gate.passed),
                "failed_gates": sum(1 for gate in self.quality_gates if not gate.passed)
            }
        }


def demo_branch_protection_pr_flow():
    """Demonstriere Branch Protection PR Flow."""
    print("🔀 Branch Protection & PR Flow Demo")
    print("=" * 60)
    
    # Test 1: Standard-PR-Flow
    print("\n✅ Test 1: Standard-PR-Flow")
    
    pr_flow = BranchProtectionPRFlow(
        repo_owner="example-org",
        repo_name="codepipeline",
        spec_id="BRANCH-DEMO-001",
        github_token=None  # Simuliert
    )
    
    # Simuliere Quality Gate-Ergebnisse
    quality_gates = [
        QualityGateStatus(
            name="Test Coverage",
            passed=True,
            score=85,
            details="85% coverage achieved",
            artifacts=["coverage_report.html"]
        ),
        QualityGateStatus(
            name="Security Scan",
            passed=True,
            score=95,
            details="No high-severity findings",
            artifacts=["security_report.json"]
        ),
        QualityGateStatus(
            name="License Check",
            passed=True,
            score=100,
            details="All licenses compliant",
            artifacts=["sbom.json", "license_report.json"]
        )
    ]
    
    for gate in quality_gates:
        pr_flow.add_quality_gate_result(gate)
    
    # Füge Artefakte hinzu
    pr_flow.add_artifact("qa_scorecard", "qa_scorecard_BRANCH-DEMO-001.json")
    pr_flow.add_artifact("security_report", "security_scan_report.json")
    pr_flow.add_artifact("sbom", "sbom_BRANCH-DEMO-001.json")
    
    # Verifiziere Branch-Protection
    protection_verified = pr_flow.verify_branch_protection()
    
    print("🔒 Branch-Protection:")
    print(f"   - Verifiziert: {'✅ YES' if protection_verified else '❌ NO'}")
    print(f"   - Main Branch: {pr_flow.main_branch}")
    print(f"   - Feature Branch: {pr_flow.feature_branch}")
    
    # Validiere Quality Gates
    all_green = pr_flow.validate_all_gates_green()
    
    print("🎯 Quality Gates:")
    print(f"   - Alle grün: {'✅ YES' if all_green else '❌ NO'}")
    print(f"   - Total: {len(pr_flow.quality_gates)}")
    print(f"   - Bestanden: {sum(1 for gate in pr_flow.quality_gates if gate.passed)}")
    
    # Erstelle Draft-PR
    if protection_verified and all_green:
        pr_result = pr_flow.create_draft_pr(
            title="Automated Feature Implementation",
            description="This feature was automatically implemented using CodePipeline.",
            changes_summary="Generated code, tests, and documentation according to specification."
        )
        
        print("📝 Draft-PR:")
        print(f"   - Erstellt: {'✅ SUCCESS' if pr_result.success else '❌ FAILED'}")
        if pr_result.success:
            print(f"   - PR Number: #{pr_result.pr_number}")
            print(f"   - Branch: {pr_result.branch_name}")
            print(f"   - Artifacts: {len(pr_result.artifacts_uploaded)}")
        else:
            print(f"   - Fehler: {pr_result.error_message}")
    
    # Test 2: Fehlgeschlagene Quality Gates
    print("\n❌ Test 2: Fehlgeschlagene Quality Gates")
    
    failed_pr_flow = BranchProtectionPRFlow(
        repo_owner="example-org",
        repo_name="codepipeline",
        spec_id="FAILED-DEMO-001"
    )
    
    # Simuliere fehlgeschlagene Gates
    failed_gates = [
        QualityGateStatus(
            name="Test Coverage",
            passed=False,
            score=45,
            details="Coverage below threshold: 45% < 80%",
        ),
        QualityGateStatus(
            name="Security Scan",
            passed=False,
            score=20,
            details="3 high-severity vulnerabilities found",
        )
    ]
    
    for gate in failed_gates:
        failed_pr_flow.add_quality_gate_result(gate)
    
    failed_all_green = failed_pr_flow.validate_all_gates_green()
    
    print("🎯 Failed Quality Gates:")
    print(f"   - Alle grün: {'✅ YES' if failed_all_green else '❌ NO'}")
    
    if not failed_all_green:
        failed_pr_result = failed_pr_flow.create_draft_pr(
            title="Failed Feature Implementation",
            description="This feature implementation failed quality gates."
        )
        
        print("📝 Failed PR-Versuch:")
        print(f"   - Erstellt: {'✅ SUCCESS' if failed_pr_result.success else '❌ FAILED (erwartet)'}")
        print(f"   - Fehler: {failed_pr_result.error_message}")
    
    # Test 3: Status-Report
    print("\n📊 Test 3: Status-Report")
    
    status_report = pr_flow.generate_status_report()
    
    print("📋 Status-Report:")
    print(f"   - Spec ID: {status_report['spec_id']}")
    print(f"   - Branch Protection: {status_report['branch_protection']['verified']}")
    print(f"   - Quality Gates: {status_report['summary']['passed_gates']}/{status_report['summary']['total_gates']}")
    print(f"   - Artifacts: {status_report['artifacts']['count']}")
    print(f"   - Ready for PR: {status_report['summary']['ready_for_pr']}")
    
    # Speichere Status-Report
    report_file = "branch_protection_status_report.json"
    with open(report_file, 'w', encoding='utf-8') as f:
        json.dump(status_report, f, indent=2, ensure_ascii=False)
    
    print(f"💾 Status-Report gespeichert: {report_file}")
    
    # Test 4: PR-Content-Vorschau
    print("\n📄 Test 4: PR-Content-Vorschau")
    
    pr_content = pr_flow.generate_pr_content(
        title="Automated Feature Implementation",
        description="Complete feature implementation with all quality gates.",
        changes_summary="Added new functionality, tests, and documentation."
    )
    
    print(f"📝 PR-Titel: {pr_content['title']}")
    print(f"📄 PR-Beschreibung ({len(pr_content['description'])} Zeichen):")
    print(pr_content['description'][:400] + "..." if len(pr_content['description']) > 400 else pr_content['description'])
    
    print("\n✅ Branch Protection & PR Flow Demo abgeschlossen!")
    print("🔀 Vollständiger PR-Workflow mit Branch-Protection und Artefakt-Integration")
    
    return 0 if all_green else 1


if __name__ == "__main__":
    exit_code = demo_branch_protection_pr_flow()
    sys.exit(exit_code)
