"""
Auto-Documentation Generator für nutzbare Doku out-of-the-box.

Implementiert:
- Automatische README, Betriebsnotiz und API-Skizze aus Plan und Template
- Jede App enthält Startanleitung und kurze API-Übersicht
- Template-basierte Dokumentations-Generierung
"""

from __future__ import annotations

import os
import re
import json
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from pathlib import Path
from typing import Dict, List, Optional, Any, Union
import logging


logger = logging.getLogger(__name__)


class DocumentationType(Enum):
    """Dokumentations-Typen."""
    README = "readme"
    API_DOCS = "api_docs"
    DEPLOYMENT_GUIDE = "deployment_guide"
    TROUBLESHOOTING = "troubleshooting"
    CHANGELOG = "changelog"
    CONTRIBUTING = "contributing"


class ProgramType(Enum):
    """Programm-Typen."""
    CLI = "cli"
    WEB_API = "web_api"
    WORKER = "worker"
    BATCH = "batch"


@dataclass
class DocumentationTemplate:
    """Dokumentations-Template."""
    
    template_id: str
    name: str
    description: str
    doc_type: DocumentationType
    program_types: List[ProgramType] = field(default_factory=list)
    
    # Template-Inhalt
    template_content: str = ""
    
    # Variablen
    required_variables: List[str] = field(default_factory=list)
    optional_variables: List[str] = field(default_factory=list)
    
    # Metadaten
    author: str = "CodePipeline"
    version: str = "1.0.0"
    
    def to_dict(self) -> Dict[str, Any]:
        """Konvertiere zu Dictionary."""
        return {
            "template_id": self.template_id,
            "name": self.name,
            "description": self.description,
            "doc_type": self.doc_type.value,
            "program_types": [pt.value for pt in self.program_types],
            "required_variables": self.required_variables,
            "optional_variables": self.optional_variables,
            "author": self.author,
            "version": self.version
        }


@dataclass
class DocumentationContext:
    """Dokumentations-Kontext."""
    
    # Programm-Info
    program_name: str
    program_type: ProgramType
    program_version: str = "1.0.0"
    program_description: str = ""
    
    # Plan-Info
    plan_goal: str = ""
    plan_features: List[str] = field(default_factory=list)
    plan_constraints: List[str] = field(default_factory=list)
    
    # API-Info
    api_endpoints: List[Dict[str, Any]] = field(default_factory=list)
    api_base_url: str = "http://localhost:5000"
    
    # CLI-Info
    cli_commands: List[Dict[str, Any]] = field(default_factory=list)
    cli_usage: str = ""
    
    # Deployment-Info
    port: int = 5000
    environment_variables: List[Dict[str, Any]] = field(default_factory=list)
    dependencies: List[str] = field(default_factory=list)
    
    # Metadaten
    author: str = "Generated by CodePipeline"
    license: str = "MIT"
    repository_url: str = ""
    
    def to_dict(self) -> Dict[str, Any]:
        """Konvertiere zu Dictionary für Template-Rendering."""
        return {
            "program_name": self.program_name,
            "program_type": self.program_type.value,
            "program_version": self.program_version,
            "program_description": self.program_description,
            "plan_goal": self.plan_goal,
            "plan_features": self.plan_features,
            "plan_constraints": self.plan_constraints,
            "api_endpoints": self.api_endpoints,
            "api_base_url": self.api_base_url,
            "cli_commands": self.cli_commands,
            "cli_usage": self.cli_usage,
            "port": self.port,
            "environment_variables": self.environment_variables,
            "dependencies": self.dependencies,
            "author": self.author,
            "license": self.license,
            "repository_url": self.repository_url,
            "generated_at": datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")
        }


class TemplateRenderer:
    """Template-Renderer für Dokumentation."""
    
    def __init__(self):
        self.variable_pattern = re.compile(r'\\{\\{\\s*([\\w_]+)\\s*\\}\\}')
        self.conditional_pattern = re.compile(r'\\{%\\s*if\\s+([\\w_]+)\\s*%\\}(.*?)\\{%\\s*endif\\s*%\\}', re.DOTALL)
        self.loop_pattern = re.compile(r'\\{%\\s*for\\s+(\\w+)\\s+in\\s+(\\w+)\\s*%\\}(.*?)\\{%\\s*endfor\\s*%\\}', re.DOTALL)
    
    def render(self, template_content: str, context: Dict[str, Any]) -> str:
        """Rendere Template mit Kontext."""
        
        try:
            rendered = template_content
            
            # Verarbeite Schleifen
            rendered = self._process_loops(rendered, context)
            
            # Verarbeite Conditionals
            rendered = self._process_conditionals(rendered, context)
            
            # Ersetze Variablen
            rendered = self._substitute_variables(rendered, context)
            
            # Bereinige leere Zeilen
            rendered = self._cleanup_empty_lines(rendered)
            
            return rendered
        
        except Exception as e:
            logger.error(f"Template rendering failed: {e}")
            return template_content
    
    def _process_loops(self, content: str, context: Dict[str, Any]) -> str:
        """Verarbeite For-Schleifen."""
        
        def replace_loop(match):
            item_var = match.group(1)
            list_var = match.group(2)
            loop_content = match.group(3)
            
            if list_var in context and isinstance(context[list_var], list):
                rendered_items = []
                
                for item in context[list_var]:
                    # Erstelle Kontext für Loop-Item
                    loop_context = context.copy()
                    loop_context[item_var] = item
                    
                    # Rendere Loop-Inhalt
                    rendered_item = self._substitute_variables(loop_content, loop_context)
                    rendered_items.append(rendered_item)
                
                return "\\n".join(rendered_items)
            else:
                return ""
        
        return self.loop_pattern.sub(replace_loop, content)
    
    def _process_conditionals(self, content: str, context: Dict[str, Any]) -> str:
        """Verarbeite If-Conditionals."""
        
        def replace_conditional(match):
            condition_var = match.group(1)
            conditional_content = match.group(2)
            
            # Prüfe Bedingung
            if condition_var in context:
                value = context[condition_var]
                
                # Truthy-Check
                if value and (not isinstance(value, list) or len(value) > 0):
                    return conditional_content
            
            return ""
        
        return self.conditional_pattern.sub(replace_conditional, content)
    
    def _substitute_variables(self, content: str, context: Dict[str, Any]) -> str:
        """Ersetze Template-Variablen."""
        
        def replace_variable(match):
            var_name = match.group(1)
            
            if var_name in context:
                value = context[var_name]
                
                # Konvertiere zu String
                if isinstance(value, (list, dict)):
                    if isinstance(value, list) and all(isinstance(item, str) for item in value):
                        return ", ".join(value)
                    else:
                        return json.dumps(value, indent=2)
                else:
                    return str(value)
            else:
                # Unbekannte Variable - behalte Placeholder
                return f"[{var_name}]"
        
        return self.variable_pattern.sub(replace_variable, content)
    
    def _cleanup_empty_lines(self, content: str) -> str:
        """Bereinige überflüssige leere Zeilen."""
        
        # Entferne mehrere aufeinanderfolgende leere Zeilen
        content = re.sub(r'\\n\\s*\\n\\s*\\n+', '\\n\\n', content)
        
        # Entferne leere Zeilen am Anfang und Ende
        content = content.strip()
        
        return content


class AutoDocumentationGenerator:
    """Auto-Documentation Generator."""
    
    def __init__(self):
        self.templates: Dict[str, DocumentationTemplate] = {}
        self.renderer = TemplateRenderer()
        self._load_default_templates()
    
    def _load_default_templates(self):
        """Lade Standard-Templates."""
        
        # README Template
        readme_template = DocumentationTemplate(
            template_id="readme_standard",
            name="Standard README",
            description="Standard README template for all program types",
            doc_type=DocumentationType.README,
            program_types=[ProgramType.CLI, ProgramType.WEB_API, ProgramType.WORKER, ProgramType.BATCH],
            template_content=self._get_readme_template(),
            required_variables=["program_name", "program_description", "program_type"],
            optional_variables=["plan_goal", "plan_features", "api_endpoints", "cli_commands"]
        )
        
        # API Documentation Template
        api_docs_template = DocumentationTemplate(
            template_id="api_docs_standard",
            name="Standard API Documentation",
            description="API documentation template for web APIs",
            doc_type=DocumentationType.API_DOCS,
            program_types=[ProgramType.WEB_API],
            template_content=self._get_api_docs_template(),
            required_variables=["program_name", "api_base_url"],
            optional_variables=["api_endpoints"]
        )
        
        # Deployment Guide Template
        deployment_template = DocumentationTemplate(
            template_id="deployment_standard",
            name="Standard Deployment Guide",
            description="Deployment guide for all program types",
            doc_type=DocumentationType.DEPLOYMENT_GUIDE,
            program_types=[ProgramType.CLI, ProgramType.WEB_API, ProgramType.WORKER, ProgramType.BATCH],
            template_content=self._get_deployment_template(),
            required_variables=["program_name", "program_type"],
            optional_variables=["port", "environment_variables", "dependencies"]
        )
        
        # Troubleshooting Template
        troubleshooting_template = DocumentationTemplate(
            template_id="troubleshooting_standard",
            name="Standard Troubleshooting Guide",
            description="Troubleshooting guide for common issues",
            doc_type=DocumentationType.TROUBLESHOOTING,
            program_types=[ProgramType.CLI, ProgramType.WEB_API, ProgramType.WORKER, ProgramType.BATCH],
            template_content=self._get_troubleshooting_template(),
            required_variables=["program_name", "program_type"],
            optional_variables=["port"]
        )
        
        # Registriere Templates
        for template in [readme_template, api_docs_template, deployment_template, troubleshooting_template]:
            self.templates[template.template_id] = template
    
    def _get_readme_template(self) -> str:
        """README Template."""
        return '''# {{program_name}}

{{program_description}}

{% if plan_goal %}
## Goal

{{plan_goal}}
{% endif %}

{% if plan_features %}
## Features

{% for feature in plan_features %}
- {{feature}}
{% endfor %}
{% endif %}

## Installation

```bash
# Clone the repository
git clone {{repository_url}}
cd {{program_name}}

# Install dependencies
pip install -r requirements.txt
```

## Usage

{% if program_type == "cli" %}
### Command Line Usage

```bash
python main.py --help
```

{% if cli_commands %}
### Available Commands

{% for command in cli_commands %}
- `{{command.name}}`: {{command.description}}
{% endfor %}
{% endif %}

{% elif program_type == "web_api" %}
### Starting the API Server

```bash
python main.py
```

The API will be available at: {{api_base_url}}

{% if api_endpoints %}
### API Endpoints

{% for endpoint in api_endpoints %}
- `{{endpoint.method}} {{endpoint.path}}`: {{endpoint.description}}
{% endfor %}
{% endif %}

{% elif program_type == "worker" %}
### Starting the Worker

```bash
python main.py
```

The worker will process tasks from the configured queue.

{% elif program_type == "batch" %}
### Running the Batch Job

```bash
python main.py
```

The batch job will process the configured data sources.
{% endif %}

## Configuration

{% if environment_variables %}
### Environment Variables

{% for env_var in environment_variables %}
- `{{env_var.name}}`: {{env_var.description}} {% if env_var.required %}(Required){% else %}(Optional){% endif %}
{% endfor %}
{% endif %}

## Development

### Running Tests

```bash
pytest
```

### Code Formatting

```bash
black .
isort .
```

## License

This project is licensed under the {{license}} License.

## Generated

This documentation was automatically generated by CodePipeline on {{generated_at}}.
'''
    
    def _get_api_docs_template(self) -> str:
        """API Documentation Template."""
        return '''# {{program_name}} API Documentation

Base URL: `{{api_base_url}}`

## Overview

This document describes the REST API for {{program_name}}.

## Authentication

{% if api_endpoints %}
## Endpoints

{% for endpoint in api_endpoints %}
### {{endpoint.method}} {{endpoint.path}}

{{endpoint.description}}

{% if endpoint.parameters %}
**Parameters:**
{% for param in endpoint.parameters %}
- `{{param.name}}` ({{param.type}}): {{param.description}} {% if param.required %}*Required*{% endif %}
{% endfor %}
{% endif %}

{% if endpoint.example_request %}
**Example Request:**
```bash
curl -X {{endpoint.method}} "{{api_base_url}}{{endpoint.path}}" \\
  -H "Content-Type: application/json"{% if endpoint.example_request %} \\
  -d '{{endpoint.example_request}}'{% endif %}
```
{% endif %}

{% if endpoint.example_response %}
**Example Response:**
```json
{{endpoint.example_response}}
```
{% endif %}

---
{% endfor %}
{% endif %}

## Error Handling

All API errors return JSON with the following structure:

```json
{
  "error": {
    "code": "ERROR_CODE",
    "message": "Human readable error message"
  }
}
```

## Status Codes

- `200 OK`: Request successful
- `400 Bad Request`: Invalid request parameters
- `401 Unauthorized`: Authentication required
- `404 Not Found`: Resource not found
- `500 Internal Server Error`: Server error

## Rate Limiting

API requests are rate limited to prevent abuse. Current limits:
- 1000 requests per hour per IP address
- 100 requests per minute per IP address

## Generated

This API documentation was automatically generated on {{generated_at}}.
'''
    
    def _get_deployment_template(self) -> str:
        """Deployment Guide Template."""
        return '''# {{program_name}} Deployment Guide

This guide covers how to deploy {{program_name}} in different environments.

## Prerequisites

- Python 3.8 or higher
- Docker (optional)
{% if dependencies %}
- Additional dependencies: {{dependencies}}
{% endif %}

## Local Development

1. Clone the repository:
```bash
git clone {{repository_url}}
cd {{program_name}}
```

2. Create virtual environment:
```bash
python -m venv venv
source venv/bin/activate  # On Windows: venv\\Scripts\\activate
```

3. Install dependencies:
```bash
pip install -r requirements.txt
```

4. Set environment variables:
```bash
{% if environment_variables %}
{% for env_var in environment_variables %}
export {{env_var.name}}="{{env_var.default_value}}"
{% endfor %}
{% else %}
# No environment variables required
{% endif %}
```

5. Run the application:
```bash
{% if program_type == "web_api" %}
python main.py
# Access at: http://localhost:{{port}}
{% elif program_type == "cli" %}
python main.py --help
{% elif program_type == "worker" %}
python main.py
{% elif program_type == "batch" %}
python main.py
{% endif %}
```

## Docker Deployment

1. Build the Docker image:
```bash
docker build -t {{program_name}} .
```

2. Run the container:
```bash
{% if program_type == "web_api" %}
docker run -p {{port}}:{{port}} {% if environment_variables %}{% for env_var in environment_variables %}-e {{env_var.name}}="{{env_var.default_value}}" {% endfor %}{% endif %}{{program_name}}
{% else %}
docker run {% if environment_variables %}{% for env_var in environment_variables %}-e {{env_var.name}}="{{env_var.default_value}}" {% endfor %}{% endif %}{{program_name}}
{% endif %}
```

## Production Deployment

### Using Docker Compose

1. Create `docker-compose.yml`:
```yaml
version: '3.8'
services:
  {{program_name}}:
    build: .
{% if program_type == "web_api" %}
    ports:
      - "{{port}}:{{port}}"
{% endif %}
{% if environment_variables %}
    environment:
{% for env_var in environment_variables %}
      - {{env_var.name}}={{env_var.default_value}}
{% endfor %}
{% endif %}
    restart: unless-stopped
```

2. Start the service:
```bash
docker-compose up -d
```

## Health Checks

{% if program_type == "web_api" %}
The application provides a health check endpoint:
```bash
curl http://localhost:{{port}}/health
```
{% else %}
The application logs its health status to stdout.
{% endif %}

## Monitoring

- Check application logs: `docker logs {{program_name}}`
- Monitor resource usage: `docker stats {{program_name}}`

## Troubleshooting

See [TROUBLESHOOTING.md](TROUBLESHOOTING.md) for common issues and solutions.

## Generated

This deployment guide was automatically generated on {{generated_at}}.
'''
    
    def _get_troubleshooting_template(self) -> str:
        """Troubleshooting Template."""
        return '''# {{program_name}} Troubleshooting Guide

This guide helps resolve common issues with {{program_name}}.

## Common Issues

### Application Won't Start

**Symptoms:**
- Application exits immediately
- Error messages on startup

**Solutions:**
1. Check Python version: `python --version` (requires 3.8+)
2. Verify dependencies: `pip list`
3. Check environment variables
4. Review application logs

### {% if program_type == "web_api" %}Port Already in Use

**Symptoms:**
- Error: "Address already in use"
- Cannot bind to port {{port}}

**Solutions:**
1. Find process using port: `lsof -i :{{port}}` (Linux/Mac) or `netstat -ano | findstr :{{port}}` (Windows)
2. Kill the process or use a different port
3. Set PORT environment variable: `export PORT=8080`

### API Returns 500 Errors

**Symptoms:**
- Internal server errors
- 500 status codes

**Solutions:**
1. Check application logs for stack traces
2. Verify database connectivity (if applicable)
3. Check file permissions
4. Ensure all required environment variables are set
{% elif program_type == "cli" %}Command Not Found

**Symptoms:**
- "Command not found" errors
- Permission denied

**Solutions:**
1. Ensure script is executable: `chmod +x main.py`
2. Use full Python path: `/usr/bin/python3 main.py`
3. Check PATH environment variable
4. Verify Python installation
{% elif program_type == "worker" %}Worker Not Processing Tasks

**Symptoms:**
- Tasks remain in queue
- No processing activity

**Solutions:**
1. Check queue connectivity
2. Verify worker configuration
3. Check for error messages in logs
4. Ensure sufficient resources (CPU, memory)
{% elif program_type == "batch" %}Batch Job Fails

**Symptoms:**
- Job exits with error code
- Incomplete processing

**Solutions:**
1. Check input data format
2. Verify file permissions
3. Ensure sufficient disk space
4. Check for data validation errors
{% endif %}

### High Memory Usage

**Symptoms:**
- Application becomes slow
- Out of memory errors

**Solutions:**
1. Monitor memory usage: `top` or `htop`
2. Check for memory leaks in logs
3. Increase available memory
4. Optimize data processing

### Performance Issues

**Symptoms:**
- Slow response times
- High CPU usage

**Solutions:**
1. Profile the application
2. Check database query performance (if applicable)
3. Review resource limits
4. Consider scaling horizontally

## Debugging

### Enable Debug Logging

Set environment variable:
```bash
export LOG_LEVEL=DEBUG
```

### Check Application Health

{% if program_type == "web_api" %}
```bash
curl http://localhost:{{port}}/health
```
{% else %}
Check application logs for health status messages.
{% endif %}

### Collect System Information

```bash
# System information
uname -a
python --version
pip list

# Resource usage
free -h
df -h
top -n 1
```

## Getting Help

If you continue to experience issues:

1. Check the application logs for detailed error messages
2. Ensure all prerequisites are met
3. Verify configuration settings
4. Review the deployment guide

## Log Locations

- Application logs: stdout/stderr
- Container logs: `docker logs {{program_name}}`
- System logs: `/var/log/` (Linux) or Event Viewer (Windows)

## Generated

This troubleshooting guide was automatically generated on {{generated_at}}.
'''
    
    def generate_documentation(
        self,
        context: DocumentationContext,
        doc_types: List[DocumentationType] = None,
        output_dir: Path = None
    ) -> Dict[str, str]:
        """Generiere Dokumentation."""
        
        if doc_types is None:
            doc_types = [DocumentationType.README, DocumentationType.DEPLOYMENT_GUIDE]
        
        if output_dir is None:
            output_dir = Path.cwd()
        
        logger.info(f"Generating documentation for {context.program_name}")
        
        generated_docs = {}
        template_context = context.to_dict()
        
        for doc_type in doc_types:
            # Finde passende Templates
            suitable_templates = [
                template for template in self.templates.values()
                if (template.doc_type == doc_type and 
                    (not template.program_types or context.program_type in template.program_types))
            ]
            
            if not suitable_templates:
                logger.warning(f"No template found for {doc_type.value}")
                continue
            
            # Verwende erstes passendes Template
            template = suitable_templates[0]
            
            # Rendere Template
            try:
                rendered_content = self.renderer.render(template.template_content, template_context)
                
                # Bestimme Dateinamen
                filename = self._get_filename_for_doc_type(doc_type)
                file_path = output_dir / filename
                
                # Schreibe Datei
                file_path.write_text(rendered_content, encoding='utf-8')
                
                generated_docs[doc_type.value] = str(file_path)
                
                logger.info(f"Generated {doc_type.value}: {filename} ({len(rendered_content)} chars)")
            
            except Exception as e:
                logger.error(f"Failed to generate {doc_type.value}: {e}")
        
        return generated_docs
    
    def _get_filename_for_doc_type(self, doc_type: DocumentationType) -> str:
        """Bestimme Dateinamen für Dokumentations-Typ."""
        
        filenames = {
            DocumentationType.README: "README.md",
            DocumentationType.API_DOCS: "API.md",
            DocumentationType.DEPLOYMENT_GUIDE: "DEPLOYMENT.md",
            DocumentationType.TROUBLESHOOTING: "TROUBLESHOOTING.md",
            DocumentationType.CHANGELOG: "CHANGELOG.md",
            DocumentationType.CONTRIBUTING: "CONTRIBUTING.md"
        }
        
        return filenames.get(doc_type, f"{doc_type.value}.md")
    
    def create_context_from_plan(self, plan: Dict[str, Any]) -> DocumentationContext:
        """Erstelle Dokumentations-Kontext aus Plan."""
        
        program_name = plan.get("program_name", "my-app")
        program_type_str = plan.get("program_type", "web_api")
        
        try:
            program_type = ProgramType(program_type_str)
        except ValueError:
            program_type = ProgramType.WEB_API
        
        context = DocumentationContext(
            program_name=program_name,
            program_type=program_type,
            program_version=plan.get("version", "1.0.0"),
            program_description=plan.get("description", f"A {program_type_str} application"),
            plan_goal=plan.get("goal", ""),
            plan_features=plan.get("features", []),
            plan_constraints=plan.get("constraints", []),
            author=plan.get("author", "Generated by CodePipeline"),
            license=plan.get("license", "MIT")
        )
        
        # API-spezifische Informationen
        if program_type == ProgramType.WEB_API:
            context.port = plan.get("port", 5000)
            context.api_base_url = f"http://localhost:{context.port}"
            
            # Extrahiere API-Endpunkte aus Plan
            endpoints = plan.get("api_endpoints", [])
            if not endpoints and "endpoints" in plan:
                endpoints = plan["endpoints"]
            
            context.api_endpoints = endpoints
        
        # CLI-spezifische Informationen
        elif program_type == ProgramType.CLI:
            context.cli_commands = plan.get("cli_commands", [])
            context.cli_usage = plan.get("cli_usage", f"python {program_name}.py [options]")
        
        # Environment-Variablen
        env_vars = plan.get("environment_variables", [])
        if isinstance(env_vars, dict):
            # Konvertiere Dict zu List
            env_vars = [
                {
                    "name": name,
                    "description": f"Configuration for {name}",
                    "required": True,
                    "default_value": value
                }
                for name, value in env_vars.items()
            ]
        
        context.environment_variables = env_vars
        
        # Dependencies
        context.dependencies = plan.get("dependencies", [])
        
        return context


# Convenience Functions
def generate_standard_docs(
    program_name: str,
    program_type: str,
    plan: Dict[str, Any] = None,
    output_dir: Path = None
) -> Dict[str, str]:
    """
    Generiere Standard-Dokumentation für Programm.
    
    Args:
        program_name: Name des Programms
        program_type: Typ des Programms
        plan: Plan-Dictionary (optional)
        output_dir: Output-Verzeichnis
        
    Returns:
        Dictionary mit generierten Dokumentations-Dateien
    """
    
    if output_dir is None:
        output_dir = Path.cwd()
    
    if plan is None:
        plan = {}
    
    # Ergänze Plan-Daten
    plan.update({
        "program_name": program_name,
        "program_type": program_type
    })
    
    generator = AutoDocumentationGenerator()
    context = generator.create_context_from_plan(plan)
    
    # Generiere Standard-Dokumentation
    doc_types = [DocumentationType.README, DocumentationType.DEPLOYMENT_GUIDE, DocumentationType.TROUBLESHOOTING]
    
    # Füge API-Docs für Web-APIs hinzu
    if program_type == "web_api":
        doc_types.append(DocumentationType.API_DOCS)
    
    return generator.generate_documentation(context, doc_types, output_dir)


if __name__ == "__main__":
    # Demo
    import tempfile
    
    def demo_auto_documentation_generator():
        print("📚 Auto-Documentation Generator Demo:")
        
        generator = AutoDocumentationGenerator()
        
        with tempfile.TemporaryDirectory() as temp_dir:
            temp_path = Path(temp_dir)
            
            # Test 1: Erstelle Dokumentations-Kontext
            print("\\n📋 Creating documentation context:")
            
            test_plan = {
                "program_name": "user-service",
                "program_type": "web_api",
                "version": "1.2.3",
                "description": "A RESTful API for user management",
                "goal": "Provide secure user authentication and profile management",
                "features": [
                    "User registration and login",
                    "Profile management",
                    "Password reset functionality",
                    "JWT-based authentication"
                ],
                "api_endpoints": [
                    {
                        "method": "POST",
                        "path": "/auth/login",
                        "description": "Authenticate user and return JWT token",
                        "parameters": [
                            {"name": "email", "type": "string", "required": True, "description": "User email"},
                            {"name": "password", "type": "string", "required": True, "description": "User password"}
                        ]
                    },
                    {
                        "method": "GET",
                        "path": "/users/profile",
                        "description": "Get current user profile",
                        "parameters": []
                    },
                    {
                        "method": "PUT",
                        "path": "/users/profile",
                        "description": "Update user profile",
                        "parameters": [
                            {"name": "name", "type": "string", "required": False, "description": "User full name"},
                            {"name": "bio", "type": "string", "required": False, "description": "User biography"}
                        ]
                    }
                ],
                "environment_variables": [
                    {"name": "DATABASE_URL", "description": "PostgreSQL database connection string", "required": True, "default_value": "postgresql://localhost/userdb"},
                    {"name": "JWT_SECRET", "description": "Secret key for JWT token signing", "required": True, "default_value": "your-secret-key"},
                    {"name": "PORT", "description": "Port to run the server on", "required": False, "default_value": "5000"}
                ],
                "dependencies": ["Flask", "SQLAlchemy", "PyJWT"],
                "port": 5000,
                "author": "CodePipeline Demo",
                "license": "MIT"
            }
            
            context = generator.create_context_from_plan(test_plan)
            
            print(f"  ✓ Program: {context.program_name} ({context.program_type.value})")
            print(f"  ✓ Description: {context.program_description}")
            print(f"  ✓ Features: {len(context.plan_features)}")
            print(f"  ✓ API Endpoints: {len(context.api_endpoints)}")
            print(f"  ✓ Environment Variables: {len(context.environment_variables)}")
            
            # Test 2: Generiere Dokumentation
            print("\\n📝 Generating documentation:")
            
            doc_types = [
                DocumentationType.README,
                DocumentationType.API_DOCS,
                DocumentationType.DEPLOYMENT_GUIDE,
                DocumentationType.TROUBLESHOOTING
            ]
            
            generated_docs = generator.generate_documentation(context, doc_types, temp_path)
            
            print(f"  ✓ Generated {len(generated_docs)} documentation files:")
            
            for doc_type, file_path in generated_docs.items():
                file_size = Path(file_path).stat().st_size
                print(f"    - {doc_type}: {Path(file_path).name} ({file_size} bytes)")
            
            # Test 3: Zeige Dokumentations-Inhalte
            print("\\n📄 Documentation content previews:")
            
            for doc_type, file_path in list(generated_docs.items())[:2]:  # Zeige erste 2
                content = Path(file_path).read_text()
                lines = content.splitlines()
                
                print(f"\\n  {doc_type.upper()} ({Path(file_path).name}):")
                for i, line in enumerate(lines[:10], 1):  # Erste 10 Zeilen
                    print(f"    {i:2d}: {line}")
                
                if len(lines) > 10:
                    print(f"    ... ({len(lines) - 10} more lines)")
            
            # Test 4: CLI-Programm-Test
            print("\\n🖥️ Testing CLI program documentation:")
            
            cli_plan = {
                "program_name": "data-processor",
                "program_type": "cli",
                "description": "Command-line tool for data processing",
                "goal": "Process and transform data files efficiently",
                "features": ["CSV processing", "Data validation", "Format conversion"],
                "cli_commands": [
                    {"name": "process", "description": "Process input file"},
                    {"name": "validate", "description": "Validate data format"},
                    {"name": "convert", "description": "Convert between formats"}
                ],
                "cli_usage": "python data-processor.py [command] [options]"
            }
            
            cli_context = generator.create_context_from_plan(cli_plan)
            cli_docs = generator.generate_documentation(
                cli_context,
                [DocumentationType.README, DocumentationType.DEPLOYMENT_GUIDE],
                temp_path
            )
            
            print(f"  ✓ Generated CLI docs: {len(cli_docs)} files")
            
            # Test 5: Template-Rendering-Test
            print("\\n🎨 Testing template rendering:")
            
            simple_template = "Hello {{program_name}}! {% if plan_features %}Features: {% for feature in plan_features %}{{feature}}, {% endfor %}{% endif %}"
            
            rendered = generator.renderer.render(simple_template, context.to_dict())
            
            print(f"  ✓ Template: {simple_template[:50]}...")
            print(f"  ✓ Rendered: {rendered[:100]}...")
            
            # Test Akzeptanz-Kriterien
            print("\\n🎯 Acceptance criteria:")
            
            # README generiert
            readme_generated = "readme" in generated_docs and Path(generated_docs["readme"]).exists()
            
            # API-Übersicht für Web-API
            api_docs_generated = ("api_docs" in generated_docs and 
                                Path(generated_docs["api_docs"]).exists() and
                                len(context.api_endpoints) > 0)
            
            # Startanleitung in README
            if readme_generated:
                readme_content = Path(generated_docs["readme"]).read_text()
                has_installation = "Installation" in readme_content
                has_usage = "Usage" in readme_content
                startanleitung = has_installation and has_usage
            else:
                startanleitung = False
            
            # Betriebsnotiz (Deployment Guide)
            deployment_guide = "deployment_guide" in generated_docs and Path(generated_docs["deployment_guide"]).exists()
            
            # Jede App enthält Startanleitung und API-Übersicht
            complete_documentation = (readme_generated and 
                                    startanleitung and 
                                    (api_docs_generated or context.program_type != ProgramType.WEB_API) and
                                    deployment_guide)
            
            print(f"  ✓ README generated: {readme_generated}")
            print(f"  ✓ API docs generated (for web API): {api_docs_generated}")
            print(f"  ✓ Installation and usage instructions: {startanleitung}")
            print(f"  ✓ Deployment guide generated: {deployment_guide}")
            print(f"  ✓ Complete documentation package: {complete_documentation}")
            
            return (readme_generated and startanleitung and 
                   deployment_guide and complete_documentation)
    
    # Führe Demo aus
    try:
        result = demo_auto_documentation_generator()
        print(f"\\nDemo completed successfully: {result}")
    except Exception as e:
        print(f"\\nDemo failed: {e}")
        result = False
    
    print("\\nDemo completed!")
