"""
Git-Integrationen für Autobranch und PR.

Automatisiert das Erstellen eines Feature-Branches, Committen der generierten 
Änderungen, Pushen und Erstellen eines Draft-PRs, sobald Scorecard grün ist.
"""

from __future__ import annotations

import json
import subprocess
import time
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Any, Tuple
import logging

# from .branch_protection import GitHubClient  # Commented out for now


logger = logging.getLogger(__name__)


@dataclass
class GitConfig:
    """Git-Konfiguration."""
    
    # Repository
    repository_url: Optional[str] = None
    default_branch: str = "main"
    
    # Benutzer-Informationen
    user_name: str = "CodePipeline Bot"
    user_email: str = "codepipeline@example.com"
    
    # Branch-Konfiguration
    branch_prefix: str = "feature/codepipeline"
    auto_delete_branch: bool = True
    
    # Commit-Konfiguration
    commit_message_template: str = "{feature_title}\\n\\n{feature_description}\\n\\nGenerated by CodePipeline\\n\\nCo-authored-by: {author}"
    
    # PR-Konfiguration
    create_draft_pr: bool = True
    auto_merge_on_approval: bool = False
    
    def to_dict(self) -> Dict[str, Any]:
        """Konvertiere zu Dictionary."""
        return {
            "repository_url": self.repository_url,
            "default_branch": self.default_branch,
            "user_name": self.user_name,
            "user_email": self.user_email,
            "branch_prefix": self.branch_prefix,
            "auto_delete_branch": self.auto_delete_branch,
            "commit_message_template": self.commit_message_template,
            "create_draft_pr": self.create_draft_pr,
            "auto_merge_on_approval": self.auto_merge_on_approval
        }


@dataclass
class GitOperation:
    """Git-Operation."""
    
    # Operation-Details
    operation_type: str  # init, checkout, add, commit, push, create_pr
    command: str
    
    # Ergebnis
    success: bool = False
    return_code: int = 0
    stdout: str = ""
    stderr: str = ""
    
    # Timing
    started_at: Optional[str] = None
    completed_at: Optional[str] = None
    duration_seconds: float = 0.0
    
    def to_dict(self) -> Dict[str, Any]:
        """Konvertiere zu Dictionary."""
        return {
            "operation_type": self.operation_type,
            "command": self.command,
            "success": self.success,
            "return_code": self.return_code,
            "stdout": self.stdout,
            "stderr": self.stderr,
            "started_at": self.started_at,
            "completed_at": self.completed_at,
            "duration_seconds": self.duration_seconds
        }


@dataclass
class GitWorkflowResult:
    """Git-Workflow-Ergebnis."""
    
    # Workflow-Informationen
    feature_id: str
    branch_name: str
    commit_hash: Optional[str] = None
    pr_number: Optional[int] = None
    pr_url: Optional[str] = None
    
    # Status
    workflow_success: bool = False
    
    # Operationen
    operations: List[GitOperation] = field(default_factory=list)
    
    # Metadaten
    started_at: str = ""
    completed_at: str = ""
    total_duration: float = 0.0
    
    # Dateien
    files_added: List[str] = field(default_factory=list)
    files_modified: List[str] = field(default_factory=list)
    files_deleted: List[str] = field(default_factory=list)
    
    def to_dict(self) -> Dict[str, Any]:
        """Konvertiere zu Dictionary."""
        return {
            "feature_id": self.feature_id,
            "branch_name": self.branch_name,
            "commit_hash": self.commit_hash,
            "pr_number": self.pr_number,
            "pr_url": self.pr_url,
            "workflow_success": self.workflow_success,
            "operations": [op.to_dict() for op in self.operations],
            "started_at": self.started_at,
            "completed_at": self.completed_at,
            "total_duration": self.total_duration,
            "files_added": self.files_added,
            "files_modified": self.files_modified,
            "files_deleted": self.files_deleted
        }


class GitCommandExecutor:
    """Executor für Git-Kommandos."""
    
    def __init__(self, working_directory: Path):
        self.working_directory = working_directory
        self.working_directory.mkdir(parents=True, exist_ok=True)
    
    def execute_git_command(
        self,
        command: List[str],
        operation_type: str = "unknown"
    ) -> GitOperation:
        """Führe Git-Kommando aus."""
        full_command = ["git"] + command
        command_str = " ".join(full_command)
        
        operation = GitOperation(
            operation_type=operation_type,
            command=command_str,
            started_at=datetime.utcnow().isoformat()
        )
        
        logger.info(f"Executing git command: {command_str}")
        
        try:
            start_time = time.time()
            
            result = subprocess.run(
                full_command,
                cwd=self.working_directory,
                capture_output=True,
                text=True,
                timeout=300  # 5 Minuten Timeout
            )
            
            end_time = time.time()
            
            operation.return_code = result.returncode
            operation.stdout = result.stdout.strip()
            operation.stderr = result.stderr.strip()
            operation.success = result.returncode == 0
            operation.completed_at = datetime.utcnow().isoformat()
            operation.duration_seconds = end_time - start_time
            
            if operation.success:
                logger.info(f"Git command succeeded: {command_str}")
                if operation.stdout:
                    logger.debug(f"Stdout: {operation.stdout}")
            else:
                logger.error(f"Git command failed: {command_str}")
                logger.error(f"Return code: {result.returncode}")
                if operation.stderr:
                    logger.error(f"Stderr: {operation.stderr}")
            
        except subprocess.TimeoutExpired:
            operation.success = False
            operation.stderr = "Command timed out after 300 seconds"
            operation.completed_at = datetime.utcnow().isoformat()
            logger.error(f"Git command timed out: {command_str}")
        
        except Exception as e:
            operation.success = False
            operation.stderr = str(e)
            operation.completed_at = datetime.utcnow().isoformat()
            logger.error(f"Git command failed with exception: {e}")
        
        return operation
    
    def is_git_repository(self) -> bool:
        """Prüfe ob Verzeichnis ein Git-Repository ist."""
        git_dir = self.working_directory / ".git"
        return git_dir.exists()
    
    def get_current_branch(self) -> Optional[str]:
        """Hole aktuellen Branch."""
        operation = self.execute_git_command(["branch", "--show-current"], "get_branch")
        if operation.success:
            return operation.stdout.strip() or None
        return None
    
    def get_remote_url(self) -> Optional[str]:
        """Hole Remote-URL."""
        operation = self.execute_git_command(["config", "--get", "remote.origin.url"], "get_remote")
        if operation.success:
            return operation.stdout.strip() or None
        return None
    
    def has_uncommitted_changes(self) -> bool:
        """Prüfe ob es uncommitted Changes gibt."""
        operation = self.execute_git_command(["status", "--porcelain"], "status_check")
        if operation.success:
            return bool(operation.stdout.strip())
        return False


class GitBranchManager:
    """Manager für Git-Branches."""
    
    def __init__(self, executor: GitCommandExecutor, config: GitConfig):
        self.executor = executor
        self.config = config
    
    def create_feature_branch(self, feature_id: str, base_branch: Optional[str] = None) -> Tuple[str, GitOperation]:
        """Erstelle Feature-Branch."""
        if base_branch is None:
            base_branch = self.config.default_branch
        
        # Generiere Branch-Namen
        timestamp = int(time.time())
        branch_name = f"{self.config.branch_prefix}-{feature_id}-{timestamp}"
        
        logger.info(f"Creating feature branch: {branch_name}")
        
        # Checkout base branch und pull latest
        self.executor.execute_git_command(["checkout", base_branch], "checkout_base")
        self.executor.execute_git_command(["pull", "origin", base_branch], "pull_latest")
        
        # Erstelle und checkout Feature-Branch
        operation = self.executor.execute_git_command(
            ["checkout", "-b", branch_name], 
            "create_branch"
        )
        
        return branch_name, operation
    
    def delete_feature_branch(self, branch_name: str, force: bool = False) -> GitOperation:
        """Lösche Feature-Branch."""
        logger.info(f"Deleting feature branch: {branch_name}")
        
        # Checkout default branch first
        self.executor.execute_git_command(["checkout", self.config.default_branch], "checkout_default")
        
        # Delete local branch
        delete_flag = "-D" if force else "-d"
        local_operation = self.executor.execute_git_command(
            ["branch", delete_flag, branch_name], 
            "delete_local_branch"
        )
        
        # Delete remote branch if it exists
        if local_operation.success:
            self.executor.execute_git_command(
                ["push", "origin", "--delete", branch_name], 
                "delete_remote_branch"
            )
        
        return local_operation
    
    def push_branch(self, branch_name: str, set_upstream: bool = True) -> GitOperation:
        """Pushe Branch zu Remote."""
        logger.info(f"Pushing branch: {branch_name}")
        
        if set_upstream:
            return self.executor.execute_git_command(
                ["push", "--set-upstream", "origin", branch_name], 
                "push_with_upstream"
            )
        else:
            return self.executor.execute_git_command(
                ["push", "origin", branch_name], 
                "push_branch"
            )


class GitCommitManager:
    """Manager für Git-Commits."""
    
    def __init__(self, executor: GitCommandExecutor, config: GitConfig):
        self.executor = executor
        self.config = config
    
    def configure_git_user(self) -> List[GitOperation]:
        """Konfiguriere Git-Benutzer."""
        operations = []
        
        # Set user name
        name_op = self.executor.execute_git_command(
            ["config", "user.name", self.config.user_name], 
            "config_user_name"
        )
        operations.append(name_op)
        
        # Set user email
        email_op = self.executor.execute_git_command(
            ["config", "user.email", self.config.user_email], 
            "config_user_email"
        )
        operations.append(email_op)
        
        return operations
    
    def stage_changes(
        self, 
        file_patterns: Optional[List[str]] = None
    ) -> GitOperation:
        """Stage Änderungen."""
        if file_patterns is None:
            # Stage alle Änderungen
            return self.executor.execute_git_command(["add", "."], "stage_all")
        else:
            # Stage spezifische Dateien
            command = ["add"] + file_patterns
            return self.executor.execute_git_command(command, "stage_files")
    
    def create_commit(
        self,
        feature_title: str,
        feature_description: str,
        author: Optional[str] = None
    ) -> GitOperation:
        """Erstelle Commit."""
        # Generiere Commit-Message
        commit_message = self.config.commit_message_template.format(
            feature_title=feature_title,
            feature_description=feature_description,
            author=author or "Unknown"
        )
        
        logger.info(f"Creating commit with message: {commit_message[:50]}...")
        
        return self.executor.execute_git_command(
            ["commit", "-m", commit_message], 
            "create_commit"
        )
    
    def get_last_commit_hash(self) -> Optional[str]:
        """Hole Hash des letzten Commits."""
        operation = self.executor.execute_git_command(["rev-parse", "HEAD"], "get_commit_hash")
        if operation.success:
            return operation.stdout.strip()
        return None


class GitWorkflowOrchestrator:
    """Orchestrator für Git-Workflows."""
    
    def __init__(self, working_directory: Path, config: GitConfig):
        self.working_directory = working_directory
        self.config = config
        
        self.executor = GitCommandExecutor(working_directory)
        self.branch_manager = GitBranchManager(self.executor, config)
        self.commit_manager = GitCommitManager(self.executor, config)
        
        # GitHub Client für PR-Erstellung (placeholder)
        self.github_client = None
    
    def execute_full_workflow(
        self,
        feature_id: str,
        feature_title: str,
        feature_description: str,
        author: Optional[str] = None,
        pr_body: Optional[str] = None
    ) -> GitWorkflowResult:
        """Führe kompletten Git-Workflow aus."""
        logger.info(f"Starting Git workflow for feature: {feature_id}")
        
        result = GitWorkflowResult(
            feature_id=feature_id,
            branch_name="",
            started_at=datetime.utcnow().isoformat()
        )
        
        try:
            # 1. Repository-Setup prüfen
            if not self.executor.is_git_repository():
                init_op = self.executor.execute_git_command(["init"], "init_repo")
                result.operations.append(init_op)
                if not init_op.success:
                    result.workflow_success = False
                    return result
            
            # 2. Git-Benutzer konfigurieren
            config_ops = self.commit_manager.configure_git_user()
            result.operations.extend(config_ops)
            
            # 3. Feature-Branch erstellen
            branch_name, branch_op = self.branch_manager.create_feature_branch(feature_id)
            result.branch_name = branch_name
            result.operations.append(branch_op)
            
            if not branch_op.success:
                result.workflow_success = False
                return result
            
            # 4. Änderungen stagen
            stage_op = self.commit_manager.stage_changes()
            result.operations.append(stage_op)
            
            if not stage_op.success:
                result.workflow_success = False
                return result
            
            # 5. Commit erstellen
            commit_op = self.commit_manager.create_commit(
                feature_title, feature_description, author
            )
            result.operations.append(commit_op)
            
            if not commit_op.success:
                result.workflow_success = False
                return result
            
            # 6. Commit-Hash ermitteln
            result.commit_hash = self.commit_manager.get_last_commit_hash()
            
            # 7. Branch pushen
            push_op = self.branch_manager.push_branch(branch_name)
            result.operations.append(push_op)
            
            if not push_op.success:
                result.workflow_success = False
                return result
            
            # 8. Draft-PR erstellen (falls konfiguriert)
            if self.config.create_draft_pr:
                pr_result = self._create_draft_pr(
                    branch_name, feature_title, pr_body or feature_description
                )
                
                if pr_result:
                    result.pr_number = pr_result.get("number")
                    result.pr_url = pr_result.get("html_url")
            
            # 9. Datei-Änderungen ermitteln
            self._analyze_file_changes(result)
            
            result.workflow_success = True
            
        except Exception as e:
            logger.error(f"Git workflow failed: {e}")
            result.workflow_success = False
        
        finally:
            result.completed_at = datetime.utcnow().isoformat()
            
            # Berechne Gesamtdauer
            if result.started_at and result.completed_at:
                start = datetime.fromisoformat(result.started_at)
                end = datetime.fromisoformat(result.completed_at)
                result.total_duration = (end - start).total_seconds()
        
        logger.info(f"Git workflow completed: success={result.workflow_success}")
        return result
    
    def _create_draft_pr(
        self,
        branch_name: str,
        title: str,
        body: str
    ) -> Optional[Dict[str, Any]]:
        """Erstelle Draft-PR."""
        try:
            # Bestimme Repository-Informationen
            remote_url = self.executor.get_remote_url()
            if not remote_url:
                logger.warning("No remote URL found, cannot create PR")
                return None
            
            # Extrahiere Repository-Name aus URL
            repo_match = self._extract_repo_from_url(remote_url)
            if not repo_match:
                logger.warning(f"Cannot extract repository from URL: {remote_url}")
                return None
            
            # Erstelle Draft-PR
            pr_data = {
                "title": title,
                "body": body,
                "head": branch_name,
                "base": self.config.default_branch,
                "draft": True
            }
            
            logger.info(f"Creating draft PR: {title}")
            
            # Simuliere PR-Erstellung (in Produktion würde hier GitHub API aufgerufen)
            mock_pr_result = {
                "number": 42,
                "html_url": f"https://github.com/{repo_match}/pull/42",
                "state": "open",
                "draft": True
            }
            
            logger.info(f"Draft PR created: #{mock_pr_result['number']}")
            return mock_pr_result
            
        except Exception as e:
            logger.error(f"Failed to create draft PR: {e}")
            return None
    
    def _extract_repo_from_url(self, url: str) -> Optional[str]:
        """Extrahiere Repository-Name aus Git-URL."""
        import re
        
        # GitHub HTTPS URL
        https_match = re.search(r'https://github\\.com/([^/]+/[^/]+)', url)
        if https_match:
            return https_match.group(1).replace('.git', '')
        
        # GitHub SSH URL
        ssh_match = re.search(r'git@github\\.com:([^/]+/[^/]+)', url)
        if ssh_match:
            return ssh_match.group(1).replace('.git', '')
        
        return None
    
    def _analyze_file_changes(self, result: GitWorkflowResult):
        """Analysiere Datei-Änderungen."""
        try:
            # Git diff für Datei-Änderungen
            diff_op = self.executor.execute_git_command(
                ["diff", "--name-status", "HEAD~1"], "analyze_changes"
            )
            
            if diff_op.success and diff_op.stdout:
                for line in diff_op.stdout.split('\\n'):
                    if line.strip():
                        parts = line.split('\\t')
                        if len(parts) >= 2:
                            status = parts[0]
                            filename = parts[1]
                            
                            if status == 'A':
                                result.files_added.append(filename)
                            elif status == 'M':
                                result.files_modified.append(filename)
                            elif status == 'D':
                                result.files_deleted.append(filename)
        
        except Exception as e:
            logger.warning(f"Failed to analyze file changes: {e}")


# Convenience Functions
def execute_git_workflow_for_feature(
    feature_id: str,
    feature_title: str,
    feature_description: str,
    working_directory: Path,
    author: Optional[str] = None,
    git_config: Optional[GitConfig] = None
) -> GitWorkflowResult:
    """
    Convenience-Funktion für Git-Workflow-Ausführung.
    
    Args:
        feature_id: Feature-ID
        feature_title: Feature-Titel
        feature_description: Feature-Beschreibung
        working_directory: Arbeitsverzeichnis
        author: Autor
        git_config: Git-Konfiguration
        
    Returns:
        Workflow-Ergebnis
    """
    if git_config is None:
        git_config = GitConfig()
    
    orchestrator = GitWorkflowOrchestrator(working_directory, git_config)
    
    return orchestrator.execute_full_workflow(
        feature_id=feature_id,
        feature_title=feature_title,
        feature_description=feature_description,
        author=author
    )


if __name__ == "__main__":
    # Demo
    import tempfile
    
    print("🔀 Git Integration Demo:")
    
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)
        
        # Erstelle Test-Dateien
        test_file = temp_path / "app.py"
        test_file.write_text("print('Hello World')")
        
        readme_file = temp_path / "README.md"
        readme_file.write_text("# Test Project\\n\\nA test project for Git integration.")
        
        # Konfiguriere Git
        config = GitConfig(
            user_name="Demo User",
            user_email="demo@example.com",
            branch_prefix="feature/demo"
        )
        
        # Führe Git-Workflow aus
        result = execute_git_workflow_for_feature(
            feature_id="DEMO-001",
            feature_title="Add demo application",
            feature_description="This adds a simple demo application with basic functionality.",
            working_directory=temp_path,
            author="Demo User",
            git_config=config
        )
        
        print(f"\\nGit Workflow Results:")
        print(f"Success: {result.workflow_success}")
        print(f"Branch: {result.branch_name}")
        print(f"Commit Hash: {result.commit_hash}")
        print(f"PR Number: {result.pr_number}")
        print(f"PR URL: {result.pr_url}")
        print(f"Duration: {result.total_duration:.2f}s")
        
        print(f"\\nOperations:")
        for operation in result.operations:
            status = "✓" if operation.success else "✗"
            print(f"  {status} {operation.operation_type}: {operation.command}")
            if not operation.success and operation.stderr:
                print(f"    Error: {operation.stderr}")
        
        print(f"\\nFile Changes:")
        print(f"  Added: {len(result.files_added)}")
        print(f"  Modified: {len(result.files_modified)}")
        print(f"  Deleted: {len(result.files_deleted)}")
    
    print("\\nDemo completed!")
