name: Budget Guard

on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:
  schedule:
    - cron: '30 4 * * *'  # 04:30 UTC daily budget scan

permissions:
  contents: read
  pull-requests: write

jobs:
  budget:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install cost tooling
        run: |
          pip install -U pip
          pip install infracost
      - name: Infracost breakdown
        env:
          INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
        run: |
          infracost breakdown --path . --format json --out-file infracost.json || true
      - name: Parse & Gate
        run: |
          python - <<'PY'
          import json, os
          THRESHOLD= float(os.getenv('BUDGET_THRESHOLD','100.0'))
          try:
              data=json.load(open('infracost.json'))
              total = data['projects'][0]['breakdown']['totalMonthlyCost'] if data['projects'] else 0
          except Exception:
              total=0
          print('Estimated monthly cost:', total)
          if total>THRESHOLD:
              open('comment.txt','w').write(f'⚠️ Budget überschritten: {total} > {THRESHOLD}')
              exit(1)
          else:
              open('comment.txt','w').write(f'✅ Budget innerhalb Limit: {total} ≤ {THRESHOLD}')
          PY
      - name: PR comment
        if: github.event_name == 'pull_request'
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: $(cat comment.txt)
          comment_tag: budget-check