name: Feature Request Bot

on:
  issues:
    types: [opened, edited, labeled]
  issue_comment:
    types: [created]
  workflow_dispatch:

permissions:
  issues: write
  contents: read

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Apply feature label
        if: >-
          github.event_name == 'issues' &&
          contains(github.event.issue.title, 'feature') &&
          !contains(join(github.event.issue.labels.*.name, ','), 'feature')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: feature

      - name: Add guidance comment
        if: github.event_name == 'issues' && github.event.action == 'opened'
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Danke für den Feature-Request! Das Team prüft ihn zeitnah. Bitte ergänze **Use Case**, **Business Impact** und **Akzeptanzkriterien**, falls noch nicht enthalten.