name: feature-bot
on:
  issue_comment:
    types: [created]
jobs:
  generate:
    if: startsWith(github.event.comment.body, '/generate')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.FEATURE_BOT_TOKEN }}
      - name: Set up Git
        run: |
          git config user.name "feature-bot[bot]"
          git config user.email "feature-bot@users.noreply.github.com"
      - name: Extract payload
        id: payload
        run: |
          echo "yaml<<EOF" >> $GITHUB_OUTPUT
          echo "${{ github.event.comment.body }}" | sed -e 's|^/generate\s*||' >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Generate and PR
        env:
          GH_TOKEN: ${{ secrets.FEATURE_BOT_TOKEN }}
        run: |
          ./scripts/feature_bot_generate.sh "${{ steps.payload.outputs.yaml }}"
