name: Lint

on:
  workflow_call:
    inputs:
      paths:
        description: 'Pfad(e) die gelintet werden sollen'
        required: false
        type: string
        default: 'Codepipeline502'
    secrets: {}  # keine Secrets nötig

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip
      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          python -m pip install ruff==0.5.7
      - name: Ruff
        run: ruff check ${{ inputs.paths }}
      - name: actionlint
        uses: reviewdog/action-actionlint@v1
        with:
          actionlint_flags: -color