name: Lint

on:
  workflow_call:
    inputs:
      paths:
        description: 'Pfad(e) die gelintet werden sollen'
        required: false
        type: string
        default: '.'
    secrets: {}  # keine Secrets nötig

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip
      
      - name: Install Ruff
        run: |
          python -m pip install --upgrade pip
          python -m pip install ruff
      
      - name: Lint code with Ruff
        run: ruff check ${{ inputs.paths }} --output-format=github --target-version=py312
      
      - name: Check code formatting with Ruff
        run: ruff format --diff --target-version=py312 ${{ inputs.paths }}
        continue-on-error: true