name: lint
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit hooks
        run: pre-commit run --all-files

      - name: Check type hints
        run: |
          pip install mypy
          mypy codepipeline

      - name: Check formatting
        run: |
          pip install black ruff
          black --check .
          ruff .

      - name: Compile check
        run: python -m py_compile $(find . -name '*.py')
