name: Security Auto Merge

on:
  pull_request_target:
    types: [opened, reopened, synchronize, ready_for_review, labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot-auto-merge:
    if: >-
      github.actor == 'dependabot[bot]' &&
      contains(join(fromJson(toJson(github.event.pull_request.labels)).*.name, ','), 'security')
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge
        run: |
          gh pr merge --auto --squash --delete-branch "$PR_URL"
        env:
          GH_TOKEN: ${{ secrets.DEPENDABOT_AUTO_MERGE_TOKEN || secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}